### ISSUE TITLE
(Editor not loading save) Smoked/dried/wine item variants not loading properly

### ISSUE THREAD

**Issue by VKMogwai** [colecrouter/stardew-save-editor#44]
**Describe the bug**
I tried using your save editor for the first time, but the save is not loading when I upload it. Tried on Chrome, Opera, Edge and Firefox, still not working.
But I tried looking at the browser console and it appears that _maybe_ I shouldn't have smoked salmon on my save.

```
Uncaught Error: Item "Smoked Salmon" not found in ItemData
    at new E (SaveManager.svelte.CKZBGY8g.js:1:621367)
    at SaveManager.svelte.CKZBGY8g.js:1:629574
    at Proxy.map (<anonymous>)
    at get items (SaveManager.svelte.CKZBGY8g.js:1:629511)
    at 12.3yUQuTcr.js:1:8176
    at each.Cs9BN1NY.js:1:769
    at Vt (runtime.DeBmowtN.js:1:7905)
    at W (runtime.DeBmowtN.js:1:8596)
    at q (runtime.DeBmowtN.js:1:4358)
    at wn (runtime.DeBmowtN.js:1:5049)
```
I think that is the only issue, since I tried with another save before getting some røkt laks in my inventory and it's been working properly.

**To Reproduce**
1. Open the save editor.
2. Upload my save file.
3. Stare at the background while contemplating existence.
4. Realize that the save is actually not loading.
5. Eat smoked salmon and continue to stare indefinitely.

**Expected behavior**
I expected to be amazed by the save editor, not just by its (equally amazing) background.

**Screenshots**
![image](https://github.com/user-attachments/assets/1a88cd21-55fe-49b5-9c02-e9711a362fa1)

**Save file**
[save.zip](https://github.com/user-attachments/files/18085427/save.zip)

**Device info**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest of everything

Thank you for your time and for any help you can provide!

**Comment by colecrouter** [comment]
I didn't realize there were distinct "smoked <fish>" items in the latest update. Most likely, there's some *fishy* business going on in-game, in order to make those items work.

Thanks for uploading your save, I will take a look next time I get a chance.

For the time being, if you move those items out of your inventory (e.g. a chest) you should be ok.

**Comment by colecrouter** [comment]
I've added placeholders for "invalid" items, so irregular/modded items should work now. I didn't have enough time at work to test it, but I'll try your save tomorrow.

From the looks of it, certain "preserves" have a custom sprite system (#28 had the same issue with Dried Melon, but I didn't know what was going on). I want to do a good job with that, so for now I'll look into a default/placeholder sprite for fish/dried fruit.

**Comment by colecrouter** [comment]
Should be fixed #50 
If someone could provide confirmation, that'd be awesome.
